-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.area
(
    id bigint NOT NULL DEFAULT nextval('area_id_seq'::regclass),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT area_pkey PRIMARY KEY (id),
    CONSTRAINT uk_226rm1fd8fl8ewh0a7n1k8f94 UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.area_program
(
    id bigint NOT NULL DEFAULT nextval('area_program_id_seq'::regclass),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    area_id bigint,
    CONSTRAINT area_program_pkey PRIMARY KEY (id),
    CONSTRAINT uk_lbyh8m1bc6yqnwjugxls6357h UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.city
(
    id bigint NOT NULL DEFAULT nextval('city_id_seq'::regclass),
    name character varying(159) COLLATE pg_catalog."default" NOT NULL,
    state_id bigint,
    CONSTRAINT city_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.country
(
    id bigint NOT NULL DEFAULT nextval('country_id_seq'::regclass),
    name character varying(159) COLLATE pg_catalog."default" NOT NULL,
    phonecode integer NOT NULL,
    sortname character varying(3) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT country_pkey PRIMARY KEY (id),
    CONSTRAINT uk_llidyp77h6xkeokpbmoy710d4 UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.form
(
    id bigint NOT NULL DEFAULT nextval('form_id_seq'::regclass),
    comments text COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    lastname character varying(70) COLLATE pg_catalog."default" NOT NULL,
    name character varying(70) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(15) COLLATE pg_catalog."default",
    terms boolean NOT NULL,
    area_program_id bigint,
    CONSTRAINT form_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.form_address
(
    id bigint NOT NULL DEFAULT nextval('form_address_id_seq'::regclass),
    city character varying(56) COLLATE pg_catalog."default",
    country character varying(56) COLLATE pg_catalog."default",
    state character varying(56) COLLATE pg_catalog."default",
    form_id bigint,
    CONSTRAINT form_address_pkey PRIMARY KEY (id),
    CONSTRAINT uk_kmeegrjokim6608p0gubbi8g0 UNIQUE (form_id)
);

CREATE TABLE IF NOT EXISTS public.state
(
    id bigint NOT NULL DEFAULT nextval('state_id_seq'::regclass),
    name character varying(159) COLLATE pg_catalog."default" NOT NULL,
    country_id bigint,
    CONSTRAINT state_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.area_program
    ADD CONSTRAINT fkqbytvghhdgdwdga9ccnil7gyh FOREIGN KEY (area_id)
    REFERENCES public.area (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.city
    ADD CONSTRAINT fk6p2u50v8fg2y0js6djc6xanit FOREIGN KEY (state_id)
    REFERENCES public.state (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.form
    ADD CONSTRAINT fk3vvimqf1yr02ryda0ddtec410 FOREIGN KEY (area_program_id)
    REFERENCES public.area_program (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.form_address
    ADD CONSTRAINT fk6asf3hhr685s91wicnon287wp FOREIGN KEY (form_id)
    REFERENCES public.form (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uk_kmeegrjokim6608p0gubbi8g0
    ON public.form_address(form_id);


ALTER TABLE IF EXISTS public.state
    ADD CONSTRAINT fkghic7mqjt6qb9vq7up7awu0er FOREIGN KEY (country_id)
    REFERENCES public.country (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;
