# For more information: https://laravel.com/docs/sail
version: '3'
services:
    postgresdb:
        image: postgres
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        ports:
            - $DB_PORT:5432
        volumes:
            - db:/var/lib/postgres
        networks:
            - sail
    app-server:
        depends_on:
            - postgresdb
        build: ./fnbr-form-serve
        restart: on-failure
        env_file: ./.env
        ports:
            - 8081:8081

        networks:
            - sail
    app-frotend:
        build: ./fnbr-form-app
        ports:
            - 3000:8081

networks:
    sail:
        driver: bridge
volumes:
    sail-postgresql:
        driver: local
    sail-mongodb:
        driver: local
